steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/lofty-apex-422010/test:${SHORT_SHA}', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lofty-apex-422010/test:${SHORT_SHA}']
  id: Pushing the image to registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'test-webhook-qa', '--image', 'gcr.io/lofty-apex-422010/test:${SHORT_SHA}', '--region', 'us-central1', '--platform', 'managed', "--allow-unauthenticated"]
